import { SimulationStep, TransitMode, ESCROW_COLLATERAL_BEZ } from '../types';
import { VALIDATORS } from '../validators';

// FASE A — ORIGEN: Zona Franca (10 etapas, con validadores aduaneros)
export const buildOriginSteps = (mode: TransitMode): SimulationStep[] => [
  {
    id: 1,
    phase: 'origin',
    locationIndex: 0,
    vehicle: 'camion',
    timeMs: 3000,
    activeNodes: ['rwa', 'contract'],
    status: { rwa: 'TOKENIZADO', contract: `Escrow LOCKED`, mcp: 'MCP Oracle Sync', oraculo: 'DPP Minted' },
    msg: 'Fábrica de Origen: Se digitaliza el lote físico agroalimentario como Activo del Mundo Real (RWA) mediante un Pasaporte Digital de Producto (DPP) tokenizado en un NFT BCM (ERC-721). Los tokens $BEZ colaterales se bloquean en el Smart Contract de Escrow en Polygon L2, asegurando la liquidez transaccional sin intermediarios.',
    bc: `TX L2: 0x5a2d...9b1f | MINT: BCM-NFT DPP | Escrow: lockedCollateral(${ESCROW_COLLATERAL_BEZ} BEZ)`,
    bUidStage: 'CREATED',
    actor: 'fabricante',
    escrow: 'LOCKED',
    validator: VALIDATORS.fabricante,
    metrics: { km: 0, co2: 0, fuel: 0 },
    telemetry: { temp: '22.4°C', humidity: '45%', shock: '0.0g', status: 'Integrity OK' },
    validations: [
      '[TOKENIZACIÓN] Pasaporte Digital de Producto (DPP) generado y anclado a hash IPFS inmutable.',
      '[SMART CONTRACT] Colateral del contrato de garantía verificado y bloqueado en depósito multifirma.',
      '[LEDGER] Identidad Auto-soberana (SSIaaS) del fabricante vinculada al DID del emisor.',
    ],
  },
  {
    id: 2,
    phase: 'origin',
    locationIndex: 1,
    vehicle: 'camion',
    timeMs: 2800,
    activeNodes: ['oraculo', 'mcp'],
    status: { rwa: 'EMBALAJE RFID', contract: 'Sensors Bound', mcp: 'Food Oracle Scan', oraculo: 'IoT Linked' },
    msg: 'Embalaje RFID (Operador Logístico): El lote se precinta con etiquetas RFID/NFC y sensores IoT de temperatura, humedad e impacto que quedan vinculados criptográficamente al DPP. El BeZhas Food Oracle ejecuta el escaneo bioquímico inicial (biomasa, volumetría LiDAR y perfil enzimático) sellando la línea base de calidad on-chain.',
    bc: 'ORACLE: FOOD_SCAN_BASELINE | RFID: TAG-8842-CAD | Sensors bound to DPP hash 0x7c1a...e4',
    bUidStage: 'PACKAGED',
    actor: 'operador',
    escrow: 'LOCKED',
    validator: VALIDATORS.operador,
    metrics: { km: 3, co2: 2, fuel: 1 },
    telemetry: { temp: '21.8°C', humidity: '46%', shock: '0.1g', status: 'Integrity OK' },
    validations: [
      '[ORÁCULO] Escaneo bioquímico inicial del Food Oracle registrado como línea base de calidad.',
      '[IoT] Sensores de cadena de frío emparejados con el B-UID mediante firma criptográfica.',
      '[LEDGER] Etiqueta RFID anclada al Pasaporte Digital de Producto (DPP).',
    ],
  },
  {
    id: 3,
    phase: 'origin',
    locationIndex: 2,
    vehicle: 'camion',
    timeMs: 3200,
    activeNodes: ['oraculo'],
    status: { rwa: 'EN RUTA A ZF', contract: 'Telemetry Live', mcp: 'Route Agent', oraculo: 'GPS Stream' },
    msg: 'Transporte a Zona Franca (Transportista Local): El camión frigorífico inicia el trayecto hacia el recinto fiscal. La telemetría de posición GPS, temperatura y vibración se transmite encriptada a los validadores L2 en tiempo real, quedando cada lectura anclada al ledger.',
    bc: 'ORACLE STREAM: GPS+TEMP+SHOCK @2s | Route: Origen -> Zona Franca | Anchor: 0x2f8b...c3',
    bUidStage: 'IN_TRANSIT_LOCAL',
    actor: 'transportista',
    escrow: 'LOCKED',
    validator: VALIDATORS.transportista,
    metrics: { km: 18, co2: 14, fuel: 6 },
    telemetry: { temp: '5.2°C', humidity: '84%', shock: '0.4g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[FLOTAS] Carta de porte digital local emitida con firma eIDAS del transportista.',
      '[ORÁCULO] Telemetría refrigerada en vivo (temperatura idónea 5.5°C) validada por nodos L2.',
      '[LEDGER] Geocerca (geofencing) del corredor Origen-Zona Franca activada en el smart contract.',
    ],
  },
  {
    id: 4,
    phase: 'origin',
    locationIndex: 2,
    vehicle: 'camion',
    timeMs: 2500,
    activeNodes: ['contract', 'mcp'],
    status: { rwa: 'ACCESO ZF', contract: 'Gate Check OK', mcp: 'DID Verifier', oraculo: 'RFID Match' },
    msg: 'Acceso Zona Franca (Consorcio ZF): En la puerta de control, el sistema verifica el DID del transportista y el precinto RFID contra el ledger. La mercancía entra en régimen de depósito franco: el smart contract registra la suspensión de aranceles e IVA mientras permanezca en el recinto.',
    bc: 'GATE: DID_VERIFIED did:log:transportista | RFID MATCH 100% | Regime: FRANCO_SUSPENSIVO',
    bUidStage: 'ZF_ADMITTED',
    actor: 'consorcio_zf',
    escrow: 'LOCKED',
    validator: VALIDATORS.consorcioZF,
    metrics: { km: 25, co2: 19, fuel: 8 },
    telemetry: { temp: '5.0°C', humidity: '85%', shock: '0.2g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[ZF] Verificación de identidad descentralizada (DID) del transportista en la puerta de control.',
      '[SMART CONTRACT] Régimen fiscal suspensivo de Zona Franca activado on-chain.',
      '[LEDGER] Entrada al recinto franco sellada con timestamp inmutable.',
    ],
  },
  {
    id: 5,
    phase: 'origin',
    locationIndex: 3,
    vehicle: 'camion',
    timeMs: 2800,
    activeNodes: ['rwa', 'oraculo'],
    status: { rwa: 'ALMACÉN ZF', contract: 'Custody: Depósito', mcp: 'Digital Twin Sync', oraculo: 'Env. Monitor' },
    msg: 'Almacén ZF (Depósito Franco): El lote queda almacenado en cámara refrigerada del depósito franco. El Digital Twin del activo se sincroniza con las condiciones ambientales de la cámara y la custodia legal se transfiere del transportista al depositario, quedando registrada en la L2.',
    bc: 'CUSTODY: Transportista -> Depósito Franco | Twin sync: chamber CAM-04 | TX: 0x91ac...77',
    bUidStage: 'ZF_STORED',
    actor: 'deposito_zf',
    escrow: 'LOCKED',
    validator: VALIDATORS.depositoZF,
    metrics: { km: 27, co2: 20, fuel: 9 },
    telemetry: { temp: '4.8°C', humidity: '86%', shock: '0.0g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[ZF] Traspaso de custodia legal registrado de manera inmutable en el ledger.',
      '[TWIN] Digital Twin sincronizado con sensores ambientales de la cámara frigorífica.',
      '[ORÁCULO] Monitorización continua de la cadena de frío en depósito activada.',
    ],
  },
  {
    id: 6,
    phase: 'origin',
    locationIndex: 4,
    vehicle: 'camion',
    timeMs: 3000,
    activeNodes: ['oraculo', 'contract'],
    status: { rwa: 'ADUANA ORIGEN', contract: 'UBL 2.1 e-SPS', mcp: 'Customs API', oraculo: 'Green Lane OK' },
    msg: 'Validación Aduanera (Agencia Tributaria): Despacho aduanero 100% digitalizado en la Ventanilla Única Aduanera. El oráculo de BeZhas integra la API de aduanas y ASYCUDA World, validando la documentación bajo estándares UBL 2.1 y el certificado fitosanitario electrónico (e-SPS). Se otorga paso directo automatizado (Green Lane) sin retenciones.',
    bc: 'API RESOLVE: ASYCUDA_WORLD_VUA | State: GREEN_LANE_APPROVED | Sign: eIDAS_Customs_0x4a',
    bUidStage: 'CUSTOMS_CLEARED',
    actor: 'aeat',
    escrow: 'LOCKED',
    validator: VALIDATORS.aeat,
    metrics: { km: 30, co2: 22, fuel: 10 },
    telemetry: { temp: '4.9°C', humidity: '85%', shock: '0.1g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[ADUANA] Pre-declaración aduanera cruzada con éxito en la Ventanilla Única Aduanera (VUA).',
      '[TOKENIZACIÓN] Validación de conformidad fitosanitaria e-SPS sellada de manera inmutable on-chain.',
      "[ORÁCULO] Emisión del ticket de despacho aduanero digital 'Green Lane' en la L2 de BeZhas.",
    ],
  },
  {
    id: 7,
    phase: 'origin',
    locationIndex: 5,
    vehicle: 'camion',
    timeMs: 3000,
    activeNodes: ['mcp', 'oraculo'],
    status: { rwa: 'INSPECCIÓN FÍSICA', contract: 'Deep Scan Sealed', mcp: 'Aegis Vision AI', oraculo: 'Pathogen Map OK' },
    msg: 'Inspección Física (Inspector Aduanero): Inspección asistida por el Food Oracle: escaneo profundo de la carga con visión por computadora e IA, mapeando patógenos, contaminantes y frescura. El informe forense se inyecta en el DPP y el inspector firma el acta digital con su DID.',
    bc: 'ORACLE: FOOD_DEEP_SCAN | Pathogen prob: 0.1% | Acta firmada: did:etr:inspector | TX: 0x6d3e...b8',
    bUidStage: 'INSPECTED',
    actor: 'inspector',
    escrow: 'LOCKED',
    validator: VALIDATORS.inspector,
    metrics: { km: 33, co2: 24, fuel: 11 },
    telemetry: { temp: '5.1°C', humidity: '84%', shock: '0.1g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[INSPECCIÓN] Deep-scan bioquímico del Food Oracle sin colonias fúngicas activas.',
      '[IA] Análisis de visión computacional Aegis con 0% de anomalías detectadas.',
      '[LEDGER] Acta de inspección física firmada con DID e inyectada en el DPP.',
    ],
  },
  {
    id: 8,
    phase: 'origin',
    locationIndex: mode === 'sea' ? 6 : 11,
    vehicle: 'camion',
    timeMs: 3000,
    activeNodes: ['mcp', 'rwa'],
    status: mode === 'sea'
      ? { rwa: 'ESTIBA PUERTO', contract: 'Stowage Validated', mcp: 'Smart Stowage AR', oraculo: 'Safe Load OK' }
      : { rwa: 'ESTIBA AÉREA', contract: 'Weight Validated', mcp: 'Air Cargo Stowage', oraculo: 'ULD Verified' },
    msg: mode === 'sea'
      ? "Muelle de Origen (Autoridad Portuaria): Planificación y carga del contenedor refrigerado. El módulo 'Smart Stowage AR' de BeZhas calcula el centro de gravedad (COG) óptimo del buque con visión por computadora para prevenir riesgos de vuelco. El plan de estiba se valida y firma digitalmente en el ledger portuario."
      : 'Terminal Aérea de Carga: Balanceo de la carga en contenedores ULD para la aeronave. Sensores volumétricos certifican peso y dimensiones, y se genera el conocimiento de embarque aéreo digital (e-AWB) vinculado al pasaporte del activo en la blockchain.',
    bc: mode === 'sea'
      ? 'API CALL: ON_LOAD_VERIFIED | COG Margin: 98.4% | Stowage Cell ID: SEC-A25 | TX: 0x3d1b'
      : 'API CALL: ON_AIR_LOAD_CONFIRMED | ULD Net Weight: 3540 kg | Sign: IATA_eAWB_0x3e',
    bUidStage: 'STOWED',
    actor: mode === 'sea' ? 'puerto_cadiz' : 'aerolinea',
    escrow: 'LOCKED',
    validator: mode === 'sea' ? VALIDATORS.puertoCadiz : VALIDATORS.aerolinea,
    metrics: { km: 35, co2: 26, fuel: 12 },
    telemetry: { temp: '5.0°C', humidity: '83%', shock: '1.1g', status: 'Cold-chain ACTIVE' },
    validations: mode === 'sea'
      ? [
          '[PUERTO] Estiba inteligente validada mediante telemetría volumétrica y visión computacional.',
          '[SMART CONTRACT] Centro de gravedad (COG) certificado bajo estándares de seguridad marítima.',
          '[TOKENIZACIÓN] Firma digital del manifiesto electrónico de estiba en la L2 de BeZhas.',
        ]
      : [
          '[AEROPUERTO] Dimensionamiento volumétrico del contenedor ULD validado on-chain.',
          '[SMART CONTRACT] Balance de carga certificado bajo normas internacionales de aviación.',
          '[TOKENIZACIÓN] Manifiesto aéreo digital e-AWB integrado al Pasaporte de Producto.',
        ],
  },
  {
    id: 9,
    phase: 'origin',
    locationIndex: mode === 'sea' ? 6 : 11,
    vehicle: mode === 'sea' ? 'buque' : 'avion',
    timeMs: 2800,
    activeNodes: ['contract', 'rwa'],
    status: mode === 'sea'
      ? { rwa: 'CARGA EN BUQUE', contract: 'e-BL Tokenized', mcp: 'DCSA Standard', oraculo: 'Custody -> Naviera' }
      : { rwa: 'CARGA AERONAVE', contract: 'e-AWB Tokenized', mcp: 'IATA Standard', oraculo: 'Custody -> Aerolínea' },
    msg: mode === 'sea'
      ? 'Carga en Buque (Compañía Naviera): El contenedor se iza a bordo. El conocimiento de embarque digital (e-BL) se tokeniza como NFT interoperable (ERC-721) bajo estándar DCSA y la custodia se transfiere a la naviera. La póliza de seguro paramétrico de carga queda enlazada a los smart contracts de reaseguro en Polygon.'
      : 'Carga en Aeronave (Aerolínea): El ULD se embarca en el carguero. El e-AWB se tokeniza como NFT interoperable y la custodia se transfiere a la aerolínea, con póliza de seguro paramétrico aérea enlazada en la blockchain.',
    bc: mode === 'sea'
      ? 'TX L2: 0xef2c...92a1 | MINT: e-BL NFT (DCSA) | Custody: Depósito -> Naviera'
      : 'TX L2: 0xef2c...92a1 | MINT: e-AWB NFT (IATA) | Custody: Depósito -> Aerolínea',
    bUidStage: 'LOADED',
    actor: mode === 'sea' ? 'naviera' : 'aerolinea',
    escrow: 'LOCKED',
    validator: mode === 'sea' ? VALIDATORS.naviera : VALIDATORS.aerolinea,
    metrics: { km: 36, co2: 27, fuel: 12 },
    telemetry: { temp: '4.6°C', humidity: '82%', shock: '0.8g', status: 'Cold-chain ACTIVE' },
    validations: mode === 'sea'
      ? [
          '[NAVIERA] e-BL electrónico tokenizado cumpliendo los estándares globales de la DCSA.',
          '[SMART CONTRACT] Traspaso de custodia y responsabilidad legal a la naviera registrado on-chain.',
          '[TOKENIZACIÓN] Póliza de seguro paramétrico de carga enlazada a contratos de reaseguro en Polygon.',
        ]
      : [
          '[AEROLÍNEA] e-AWB tokenizado cumpliendo estándares IATA de carga aérea.',
          '[SMART CONTRACT] Traspaso de custodia y responsabilidad legal a la aerolínea registrado on-chain.',
          '[TOKENIZACIÓN] Póliza de seguro paramétrico aérea activa vinculada a desvíos de ruta.',
        ],
  },
  {
    id: 10,
    phase: 'origin',
    locationIndex: mode === 'sea' ? 6 : 11,
    vehicle: mode === 'sea' ? 'buque' : 'avion',
    timeMs: 2500,
    activeNodes: ['rwa', 'contract', 'mcp', 'oraculo'],
    status: { rwa: 'CHECKPOINT ZF', contract: 'Multi-Sig 6/6', mcp: 'Consensus Round', oraculo: 'State Anchored' },
    msg: 'Cierre Blockchain ZF (Red de Consenso BeZhas): Checkpoint multi-validador del ciclo Zona Franca. Los 6 validadores del recinto (Consorcio ZF, Agencia Tributaria, Autoridad Portuaria, depósito, operador y transportista) firman el estado agregado del activo, que se ancla como prueba criptográfica en Ethereum Mainnet antes de zarpar.',
    bc: 'CHECKPOINT: ZF_CYCLE_SEALED | Multi-sig 6/6 | L1 Anchor: 0x8ba1...f0 | Status: DEPARTED',
    bUidStage: 'DEPARTED',
    actor: 'consenso',
    escrow: 'LOCKED',
    validator: VALIDATORS.consenso,
    metrics: { km: 36, co2: 27, fuel: 12 },
    telemetry: { temp: '4.5°C', humidity: '82%', shock: '0.2g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[CONSENSO] Firma multifirma 6/6 de los validadores del recinto Zona Franca.',
      '[LEDGER] Estado agregado del ciclo ZF anclado como commitment en Ethereum L1.',
      '[SMART CONTRACT] Activo autorizado para tránsito internacional. B-UID: DEPARTED.',
    ],
  },
];
