import { SimulationStep, TransitMode, TARIFF_BEZ, PAYOUT_BEZ } from '../types';
import { VALIDATORS } from '../validators';

// FASE C — DESTINO: proceso espejo del origen hasta el Distribuidor Final
export const buildDestinationSteps = (mode: TransitMode): SimulationStep[] => [
  mode === 'sea'
    ? {
        id: 12,
        phase: 'destination',
        locationIndex: 7,
        vehicle: 'buque',
        timeMs: 3500,
        activeNodes: ['oraculo', 'rwa'],
        status: { rwa: 'DESESTIBA PUERTO', contract: 'Port Custody Set', mcp: 'Smart Crane Sync', oraculo: 'Unload Active' },
        msg: 'Puerto de Destino (Desestiba): Arribo al puerto inteligente. Grúas pórtico automatizadas descargan el contenedor sincronizadas con el pasaporte digital en la L2, registrando automáticamente el traspaso de custodia de la Naviera al operador del terminal.',
        bc: 'API CALL: ON_VESSEL_DISCHARGE | Custody: Naviera -> Operador Terminal | Crane: SMART-PORT-CR-10',
        bUidStage: 'ARRIVED',
        actor: 'terminal_destino',
        escrow: 'LOCKED',
        validator: VALIDATORS.terminalDest,
        metrics: { km: 1888, co2: 1422, fuel: 611 },
        telemetry: { temp: '4.0°C', humidity: '85%', shock: '0.8g', status: 'Cold-chain ACTIVE' },
        validations: [
          '[PUERTO] Descarga automatizada validada y mapeada en el Digital Twin del puerto destino.',
          '[TOKENIZACIÓN] Registro inmutable de transferencia de custodia y responsabilidad legal.',
          '[ORÁCULO] Auditoría instantánea de temperatura post-marítima: Correcta (4.0°C).',
        ],
      }
    : {
        id: 12,
        phase: 'destination',
        locationIndex: 12,
        vehicle: 'avion',
        timeMs: 3500,
        activeNodes: ['oraculo', 'rwa'],
        status: { rwa: 'DESCARGA AÉREA', contract: 'Air Custody Set', mcp: 'ULD Automated Sync', oraculo: 'Airport Unload' },
        msg: 'Aeropuerto de Destino: Aterrizaje del carguero. Elevadores ULD automatizados descargan la mercancía en el centro de carga aeroportuario, firmando electrónicamente la transferencia de custodia y sincronizando el estado con la L2.',
        bc: 'API CALL: ON_AIRPORT_DISCHARGE | Custody: Aerolínea -> Terminal | Loader: AP-LOAD-401',
        bUidStage: 'ARRIVED',
        actor: 'terminal_destino',
        escrow: 'LOCKED',
        validator: VALIDATORS.terminalDest,
        metrics: { km: 1138, co2: 982, fuel: 421 },
        telemetry: { temp: '1.8°C', humidity: '65%', shock: '0.4g', status: 'Landed & Unloading' },
        validations: [
          '[AEROPUERTO] Descarga automatizada validada en el centro de carga aérea de destino.',
          '[TOKENIZACIÓN] Traspaso de custodia del transportista aéreo registrado inmutablemente.',
          '[ORÁCULO] Inspección de sensores de impacto y temperatura post-vuelo: Correcta (1.8°C).',
        ],
      },
  {
    id: 13,
    phase: 'destination',
    locationIndex: 8,
    vehicle: 'camion',
    timeMs: 3200,
    activeNodes: ['oraculo', 'contract'],
    status: { rwa: 'ADUANA DESTINO', contract: 'Tariff Settled', mcp: 'Tax Oracle', oraculo: 'Release Permit' },
    msg: `Aduana de Destino (proceso espejo de la ZF): La aduana extrae la documentación encriptada del ledger de BeZhas. Un oráculo fiscal calcula automáticamente los aranceles y ejecuta la liquidación inmediata debitando ${TARIFF_BEZ} $BEZ directamente del Smart Contract de Escrow, emitiendo el levante on-chain sin retenciones físicas.`,
    bc: `TX L2: 0x9b3e...c182 | Tariff Paid: ${TARIFF_BEZ} BEZ via Escrow | Status: CUSTOMS_RELEASED`,
    bUidStage: 'CUSTOMS_CLEARED_DEST',
    actor: 'aduana_destino',
    escrow: 'LOCKED',
    validator: VALIDATORS.aduanaDestino,
    metrics: { km: 1892, co2: 1425, fuel: 612 },
    telemetry: { temp: '5.1°C', humidity: '65%', shock: '0.4g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[ADUANA] Recepción y descompresión de metadatos UBL 2.1 / EUCDM H1 del importador.',
      '[TOKENIZACIÓN] Liquidación en tiempo real (RTT) de aranceles de importación en tokens BEZ.',
      '[ORÁCULO] Emisión del ticket de levante y liberación aduanera on-chain.',
    ],
  },
  {
    id: 14,
    phase: 'destination',
    locationIndex: 9,
    vehicle: 'camion',
    timeMs: 2800,
    activeNodes: ['mcp', 'oraculo'],
    status: { rwa: 'ALMACÉN DESPACHO', contract: 'Twin Verified', mcp: 'Food Oracle Re-Scan', oraculo: 'Quality Match' },
    msg: 'Almacén de Despacho Destino: El lote entra en la cámara del centro de distribución. El Food Oracle ejecuta el escaneo de verificación post-tránsito y lo compara con la línea base de origen: la equivalencia bioquímica confirma que la calidad viajó intacta. El Digital Twin se actualiza con el estado final.',
    bc: 'ORACLE: FOOD_SCAN_VERIFY vs BASELINE | Match: 99.7% | Twin state: FINAL_STAGE',
    bUidStage: 'DISPATCH_READY',
    actor: 'terminal_destino',
    escrow: 'LOCKED',
    validator: VALIDATORS.terminalDest,
    metrics: { km: 1895, co2: 1427, fuel: 613 },
    telemetry: { temp: '4.7°C', humidity: '84%', shock: '0.1g', status: 'Cold-chain ACTIVE' },
    validations: [
      '[ORÁCULO] Escaneo Food Oracle post-tránsito comparado con línea base de origen: 99.7% match.',
      '[TWIN] Digital Twin actualizado con condiciones de cámara del centro de distribución.',
      '[LEDGER] Informe de equivalencia bioquímica inyectado en el DPP.',
    ],
  },
  {
    id: 15,
    phase: 'destination',
    locationIndex: 9,
    vehicle: 'camion',
    timeMs: 3200,
    activeNodes: ['mcp', 'oraculo'],
    status: { rwa: 'ÚLTIMA MILLA', contract: 'e-CMR Active', mcp: 'Fleet Dispatch', oraculo: 'GPS Geofence' },
    msg: 'Última Milla (Flotas Terrestres): El camión frigorífico de reparto inicia la entrega final. Se genera el e-CMR (carta de porte digital) cumpliendo el reglamento europeo eFTI, y el terminal móvil del chófer envía telemetría de temperatura y posición GPS encriptada a los validadores L2.',
    bc: 'WEBHOOK: ON_FLEET_IN_TRANSIT | Active e-CMR Ref: eCMR-80432 | GPS Geofencing Active',
    bUidStage: 'LAST_MILE',
    actor: 'lastmile',
    escrow: 'LOCKED',
    validator: VALIDATORS.lastmile,
    metrics: { km: 1925, co2: 1448, fuel: 622 },
    telemetry: { temp: '5.5°C', humidity: '60%', shock: '1.2g', status: 'Integrity OK' },
    validations: [
      '[FLOTAS] e-CMR emitido con firmas digitales bajo estándar eIDAS/eFTI en la L2.',
      '[ORÁCULO] Telemetría de cadena de frío vinculada al RWA (temperatura idónea 5.5°C).',
      '[LEDGER] Sensor de impacto (SHOCK) registrando de manera inmutable cualquier golpe en ruta.',
    ],
  },
  {
    id: 16,
    phase: 'destination',
    locationIndex: 10,
    vehicle: 'camion',
    timeMs: 3500,
    activeNodes: ['rwa', 'contract', 'mcp', 'oraculo'],
    status: { rwa: 'ENTREGADO', contract: 'Escrow RELEASED', mcp: 'PoD Verified', oraculo: 'Payout Complete' },
    msg: `Distribuidor Final: Prueba de Entrega (Proof of Delivery) digital. El destinatario firma la recepción en el Validator Terminal del chófer. Tras constatar mediante los oráculos que la cadena de frío nunca se rompió desde la Zona Franca de Origen, el Smart Contract de Escrow libera automáticamente ${PAYOUT_BEZ} $BEZ al transportista y finaliza el Pasaporte Digital de Producto.`,
    bc: `TX L2: 0x8f2d...9e44 | PoD verified | Escrow: RELEASED ${PAYOUT_BEZ} BEZ to Carrier | DPP: FINALIZED`,
    bUidStage: 'DELIVERED',
    actor: 'distribuidor',
    escrow: 'RELEASED',
    validator: VALIDATORS.distribuidor,
    metrics: { km: 1931, co2: 1452, fuel: 624 },
    telemetry: { temp: '6.0°C', humidity: '58%', shock: '0.0g', status: 'DELIVERED' },
    validations: [
      '[TOKENIZACIÓN] Prueba de Entrega (PoD) firmada con la clave privada criptográfica del cliente.',
      '[SMART CONTRACT] Liquidación automática final del Escrow (Funds Disbursed) sin retrasos.',
      '[LEDGER] ✅ Pasaporte Digital de Producto finalizado con historial completo desde la Zona Franca de Origen.',
    ],
  },
];
