'use client';

/**
 * TabSkills.tsx
 * 
 * Viewer for SKILL interaction files generated by the BeZhas AI Agent.
 * Polls GET /api/agent/skills to list recent interactions with intent, tags, and provider.
 * SuperAdmin can view full turn details (user input + agent response).
 */

import { useState, useEffect, useCallback } from 'react';
import { BrainCircuit, RefreshCw, ChevronDown, ChevronUp, Sparkles, Cpu, MessageSquare, Tag, Clock } from 'lucide-react';

interface SkillEntry {
    id: string;
    created_at: string;
    intent: string;
    tags: string[];
    channel: string;
    provider: 'gemini' | 'bezhas-local' | 'intent' | 'fallback' | string;
}

interface SkillDetail extends SkillEntry {
    turn: { user: string; agent: string };
    context: { userId: string; role: string };
}

const PROVIDER_BADGE: Record<string, { label: string; color: string }> = {
    gemini:        { label: 'Gemini', color: 'bg-blue-500/20 text-blue-300 border-blue-500/30' },
    'bezhas-local':{ label: 'BeZhas AI', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30' },
    intent:        { label: 'Intent Match', color: 'bg-purple-500/20 text-purple-300 border-purple-500/30' },
    fallback:      { label: 'Fallback', color: 'bg-gray-500/20 text-gray-300 border-gray-500/30' },
};

const INTENT_COLOR: Record<string, string> = {
    general_conversation: 'text-gray-400',
    gas_analysis:         'text-yellow-400',
    fraud_detection:      'text-red-400',
    sentiment_analysis:   'text-sky-400',
    platform_status:      'text-emerald-400',
    defi_swap:            'text-indigo-400',
    sector_query:         'text-orange-400',
    validator_status:     'text-violet-400',
    bridge_health:        'text-teal-400',
    governance:           'text-pink-400',
    rwa_management:       'text-amber-400',
    help:                 'text-gray-400',
    command:              'text-cyan-400',
};

function ProviderBadge({ provider }: { provider: string }) {
    const b = PROVIDER_BADGE[provider] ?? { label: provider, color: 'bg-white/10 text-gray-300 border-white/20' };
    return (
        <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded border ${b.color}`}>
            {b.label}
        </span>
    );
}

function TagChip({ tag }: { tag: string }) {
    return (
        <span className="text-[9px] font-bold uppercase tracking-widest px-1.5 py-0.5 rounded bg-[#0d33f2]/15 text-[#5b8af5] border border-[#0d33f2]/20">
            {tag}
        </span>
    );
}

function SkillRow({ skill }: { skill: SkillEntry }) {
    const [expanded, setExpanded] = useState(false);
    const [detail, setDetail] = useState<SkillDetail | null>(null);
    const [loading, setLoading] = useState(false);

    const loadDetail = useCallback(async () => {
        if (detail) { setExpanded(e => !e); return; }
        setLoading(true);
        try {
            const token = localStorage.getItem('bezhas_token');
            const res = await fetch(
                `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001'}/api/agent/skills/${skill.id}`,
                { headers: token ? { Authorization: `Bearer ${token}` } : {} }
            );
            if (res.ok) {
                const data = await res.json();
                setDetail(data.data);
                setExpanded(true);
            }
        } catch { /* ignore */ }
        finally { setLoading(false); }
    }, [detail, skill.id]);

    const intentColor = INTENT_COLOR[skill.intent] ?? 'text-gray-400';
    const timeAgo = (date: string) => {
        const secs = Math.floor((Date.now() - new Date(date).getTime()) / 1000);
        if (secs < 60)   return `${secs}s`;
        if (secs < 3600) return `${Math.floor(secs / 60)}m`;
        if (secs < 86400) return `${Math.floor(secs / 3600)}h`;
        return `${Math.floor(secs / 86400)}d`;
    };

    return (
        <div className="border border-white/5 rounded-lg overflow-hidden hover:border-[#0d33f2]/30 transition-colors">
            <button
                onClick={loadDetail}
                className="w-full flex items-center gap-4 p-3 text-left bg-white/2 hover:bg-white/5 transition-colors"
            >
                {/* Provider */}
                <div className="shrink-0">
                    <ProviderBadge provider={skill.provider} />
                </div>

                {/* Intent */}
                <div className={`shrink-0 w-36 text-xs font-mono font-bold ${intentColor}`}>
                    {skill.intent}
                </div>

                {/* Tags */}
                <div className="flex-1 flex flex-wrap gap-1 min-w-0">
                    {skill.tags.slice(0, 5).map(t => <TagChip key={t} tag={t} />)}
                    {skill.tags.length > 5 && (
                        <span className="text-[9px] text-gray-600">+{skill.tags.length - 5}</span>
                    )}
                </div>

                {/* Channel */}
                <div className="shrink-0 text-[10px] text-gray-500 uppercase tracking-widest">{skill.channel}</div>

                {/* Time */}
                <div className="shrink-0 flex items-center gap-1 text-[10px] text-gray-600">
                    <Clock size={10} />
                    {timeAgo(skill.created_at)}
                </div>

                {/* Expand icon */}
                <div className="shrink-0 text-gray-600">
                    {loading ? (
                        <RefreshCw size={12} className="animate-spin" />
                    ) : expanded ? (
                        <ChevronUp size={14} />
                    ) : (
                        <ChevronDown size={14} />
                    )}
                </div>
            </button>

            {/* Expanded turn detail */}
            {expanded && detail && (
                <div className="border-t border-white/5 p-4 space-y-3 bg-black/30">
                    <div>
                        <div className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 flex items-center gap-1">
                            <MessageSquare size={10} /> Usuario
                        </div>
                        <div className="text-sm text-gray-200 bg-white/5 rounded p-3 font-mono whitespace-pre-wrap">
                            {detail.turn.user}
                        </div>
                    </div>
                    <div>
                        <div className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 flex items-center gap-1">
                            <Sparkles size={10} /> Agente <span className="ml-1"><ProviderBadge provider={detail.provider} /></span>
                        </div>
                        <div className="text-sm text-[#a8c0ff] bg-[#0d33f2]/5 rounded p-3 font-mono whitespace-pre-wrap leading-relaxed">
                            {detail.turn.agent}
                        </div>
                    </div>
                    <div className="text-[10px] text-gray-600 flex gap-4">
                        <span>User: {detail.context.userId}</span>
                        <span>Role: {detail.context.role}</span>
                        <span>{new Date(detail.created_at).toLocaleString('es-ES')}</span>
                    </div>
                </div>
            )}
        </div>
    );
}

export default function TabSkills() {
    const [skills, setSkills] = useState<SkillEntry[]>([]);
    const [loading, setLoading] = useState(true);
    const [filter, setFilter] = useState<string>('all');
    const [search, setSearch] = useState('');
    const [stats, setStats] = useState({ total: 0, byProvider: {} as Record<string, number> });

    const loadSkills = useCallback(async () => {
        setLoading(true);
        try {
            const token = localStorage.getItem('bezhas_token');
            const res = await fetch(
                `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001'}/api/agent/skills?limit=100`,
                { headers: token ? { Authorization: `Bearer ${token}` } : {} }
            );
            if (res.ok) {
                const data = await res.json();
                const list: SkillEntry[] = data.data || [];
                setSkills(list);

                // Compute stats
                const byProvider: Record<string, number> = {};
                for (const s of list) {
                    byProvider[s.provider] = (byProvider[s.provider] || 0) + 1;
                }
                setStats({ total: list.length, byProvider });
            }
        } catch { /* ignore */ }
        finally { setLoading(false); }
    }, []);

    useEffect(() => { loadSkills(); }, [loadSkills]);

    // Auto-refresh every 30s
    useEffect(() => {
        const interval = setInterval(loadSkills, 30_000);
        return () => clearInterval(interval);
    }, [loadSkills]);

    const filtered = skills.filter(s => {
        if (filter !== 'all' && s.provider !== filter) return false;
        if (search && !s.intent.includes(search) && !s.tags.some(t => t.includes(search))) return false;
        return true;
    });

    const providers = ['all', ...Object.keys(stats.byProvider)];

    return (
        <div className="space-y-6 font-['Space_Grotesk']">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-[#0d33f2]/20 rounded-lg flex items-center justify-center border border-[#0d33f2]/30">
                        <BrainCircuit size={20} className="text-[#5b8af5]" />
                    </div>
                    <div>
                        <h2 className="text-lg font-bold tracking-widest uppercase text-white">SKILL Interactions</h2>
                        <p className="text-xs text-gray-500">Base de conocimiento del Agente IA</p>
                    </div>
                </div>
                <button
                    onClick={loadSkills}
                    disabled={loading}
                    className="flex items-center gap-2 px-3 py-2 text-xs font-bold uppercase tracking-widest border border-white/10 text-gray-400 hover:text-white hover:border-[#0d33f2]/50 transition-all rounded"
                >
                    <RefreshCw size={12} className={loading ? 'animate-spin' : ''} />
                    Actualizar
                </button>
            </div>

            {/* Stats row */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="bg-black/30 border border-white/5 rounded-lg p-4 text-center">
                    <div className="text-2xl font-black text-white">{stats.total}</div>
                    <div className="text-[10px] text-gray-500 uppercase tracking-widest mt-1">Total SKILLs</div>
                </div>
                {Object.entries(stats.byProvider).map(([p, count]) => {
                    const b = PROVIDER_BADGE[p] ?? { label: p, color: '' };
                    return (
                        <div key={p} className="bg-black/30 border border-white/5 rounded-lg p-4 text-center">
                            <div className="text-2xl font-black text-white">{count}</div>
                            <div className="text-[10px] text-gray-500 uppercase tracking-widest mt-1">{b.label}</div>
                        </div>
                    );
                })}
                <div className="bg-black/30 border border-white/5 rounded-lg p-4 text-center">
                    <div className="text-2xl font-black text-[#5b8af5]">
                        <Cpu size={24} className="mx-auto" />
                    </div>
                    <div className="text-[10px] text-gray-500 uppercase tracking-widest mt-1">Auto-aprendizaje</div>
                </div>
            </div>

            {/* Filters */}
            <div className="flex flex-wrap gap-2 items-center">
                {/* Provider filter */}
                <div className="flex gap-1 flex-wrap">
                    {providers.map(p => (
                        <button
                            key={p}
                            onClick={() => setFilter(p)}
                            className={`text-[10px] uppercase tracking-widest font-bold px-3 py-1 rounded border transition-colors ${
                                filter === p
                                    ? 'bg-[#0d33f2] border-[#0d33f2] text-white'
                                    : 'border-white/10 text-gray-500 hover:text-white hover:border-white/20'
                            }`}
                        >
                            {p === 'all' ? 'Todos' : (PROVIDER_BADGE[p]?.label ?? p)}
                        </button>
                    ))}
                </div>

                {/* Search */}
                <div className="flex-1 min-w-[160px]">
                    <input
                        type="text"
                        placeholder="Buscar intent o tag..."
                        value={search}
                        onChange={e => setSearch(e.target.value)}
                        className="w-full bg-black/30 border border-white/10 rounded px-3 py-1.5 text-xs text-gray-300 placeholder-gray-600 focus:outline-none focus:border-[#0d33f2]/50"
                    />
                </div>

                <span className="text-xs text-gray-600">{filtered.length} resultados</span>
            </div>

            {/* Column headers */}
            <div className="flex items-center gap-4 px-3 text-[10px] text-gray-600 uppercase tracking-widest border-b border-white/5 pb-2">
                <div className="shrink-0 w-20">Proveedor</div>
                <div className="shrink-0 w-36">Intent</div>
                <div className="flex-1">Tags</div>
                <div className="shrink-0 w-16">Canal</div>
                <div className="shrink-0 w-12">Hace</div>
                <div className="shrink-0 w-6" />
            </div>

            {/* Skills list */}
            {loading ? (
                <div className="text-center py-12 text-gray-600">
                    <RefreshCw size={24} className="animate-spin mx-auto mb-3" />
                    <p className="text-xs uppercase tracking-widest">Cargando SKILLs...</p>
                </div>
            ) : filtered.length === 0 ? (
                <div className="text-center py-12 text-gray-600">
                    <Tag size={32} className="mx-auto mb-3 opacity-30" />
                    <p className="text-xs uppercase tracking-widest">
                        {stats.total === 0
                            ? 'Sin interacciones todavía. Envía un mensaje al bot de Telegram.'
                            : 'Sin resultados para el filtro actual.'
                        }
                    </p>
                </div>
            ) : (
                <div className="space-y-1">
                    {filtered.map(skill => (
                        <SkillRow key={skill.id} skill={skill} />
                    ))}
                </div>
            )}
        </div>
    );
}
